export interface ProfileTemplate {
  id: number;
  name: string;
  fantasyName: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  bgGradient: string;
  cardBg: string;
  fontFamily: string;
  isDark: boolean;
  bgImage: string | null;
  style: string;
}

export const PROFILE_TEMPLATES: ProfileTemplate[] = [
  {
    id: 1,
    name: "Porcelán",
    fantasyName: "Porcelán",
    description: "Világos, elegáns, mészfehér és finom arany beütésekkel.",
    primaryColor: "#d4af37",
    secondaryColor: "#fffdf9",
    accentColor: "#b8972a",
    bgGradient: "from-amber-50 via-white to-amber-100/50",
    cardBg: "bg-white/95 text-slate-900 border-amber-200/60 shadow-amber-100/50",
    fontFamily: "font-serif",
    isDark: false,
    bgImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1600&h=900&fit=crop",
    style: "porcelan",
  },
  {
    id: 2,
    name: "Vadvirág",
    fantasyName: "Vadvirág",
    description: "Zöldes, természetközeli, friss és lágy organikus hangulat.",
    primaryColor: "#166534",
    secondaryColor: "#f0fdf4",
    accentColor: "#15803d",
    bgGradient: "from-emerald-50 via-teal-50/40 to-green-100/40",
    cardBg: "bg-white/90 text-emerald-950 border-emerald-200 shadow-emerald-100/50",
    fontFamily: "font-sans",
    isDark: false,
    bgImage: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1600&h=900&fit=crop",
    style: "vadvirag",
  },
  {
    id: 3,
    name: "Éjfél",
    fantasyName: "Éjfél",
    description: "Sötét, luxus mély éjfélkék arany kiemelésekkel (1. sötét sablon).",
    primaryColor: "#fbbf24",
    secondaryColor: "#0f172a",
    accentColor: "#f59e0b",
    bgGradient: "from-slate-950 via-slate-900 to-slate-950",
    cardBg: "bg-slate-900/90 text-slate-100 border-slate-700 shadow-xl",
    fontFamily: "font-serif",
    isDark: true,
    bgImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1600&h=900&fit=crop",
    style: "ejfel",
  },
  {
    id: 4,
    name: "Napfény",
    fantasyName: "Napfény",
    description: "Világos, meleg sárgás-napsütéses energiával teli megjelenés.",
    primaryColor: "#ea580c",
    secondaryColor: "#fffbeb",
    accentColor: "#d97706",
    bgGradient: "from-amber-100/60 via-orange-50 to-amber-50",
    cardBg: "bg-white/95 text-slate-900 border-orange-200 shadow-orange-100/50",
    fontFamily: "font-sans",
    isDark: false,
    bgImage: "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=1600&h=900&fit=crop",
    style: "napfeny",
  },
  {
    id: 5,
    name: "Ezerlevű",
    fantasyName: "Ezerlevű",
    description: "Letisztult, szuper-minimalista, sok fehér térrel és légies tónusokkal.",
    primaryColor: "#475569",
    secondaryColor: "#f8fafc",
    accentColor: "#334155",
    bgGradient: "from-slate-50 via-white to-slate-100/50",
    cardBg: "bg-white text-slate-800 border-slate-200 shadow-sm",
    fontFamily: "font-sans",
    isDark: false,
    bgImage: null,
    style: "ezerlevu",
  },
  {
    id: 6,
    name: "Ékszervitrin",
    fantasyName: "Ékszervitrin",
    description: "Klasszikus márvány hatású prémium szalon megjelenés.",
    primaryColor: "#9333ea",
    secondaryColor: "#faf5ff",
    accentColor: "#7e22ce",
    bgGradient: "from-purple-50 via-slate-50 to-purple-100/40",
    cardBg: "bg-white/95 text-purple-950 border-purple-200 shadow-purple-100/50",
    fontFamily: "font-serif",
    isDark: false,
    bgImage: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1600&h=900&fit=crop",
    style: "ekszervitrin",
  },
  {
    id: 7,
    name: "Neonnap",
    fantasyName: "Neonnap",
    description: "Modern, friss, életteli nyári árnyalatok fiatalos stílusban.",
    primaryColor: "#06b6d4",
    secondaryColor: "#ec4899",
    accentColor: "#3b82f6",
    bgGradient: "from-cyan-50 via-pink-50/40 to-sky-50",
    cardBg: "bg-white/95 text-slate-900 border-cyan-200 shadow-cyan-100/50",
    fontFamily: "font-sans",
    isDark: false,
    bgImage: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=1600&h=900&fit=crop",
    style: "neonnap",
  },
  {
    id: 8,
    name: "Selyem",
    fantasyName: "Selyem",
    description: "Lágy pasztell, romantikus lányos púder árnyalatok.",
    primaryColor: "#db2777",
    secondaryColor: "#fdf2f8",
    accentColor: "#be185d",
    bgGradient: "from-rose-50 via-pink-50 to-rose-100/40",
    cardBg: "bg-white/95 text-rose-950 border-rose-200 shadow-rose-100/50",
    fontFamily: "font-serif",
    isDark: false,
    bgImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1600&h=900&fit=crop",
    style: "selyem",
  },
  {
    id: 9,
    name: "Gránit",
    fantasyName: "Gránit",
    description: "Sötét, karakteres antracit-gránit luxus (2. sötét sablon).",
    primaryColor: "#38bdf8",
    secondaryColor: "#18181b",
    accentColor: "#0284c7",
    bgGradient: "from-zinc-950 via-zinc-900 to-zinc-950",
    cardBg: "bg-zinc-900/90 text-zinc-100 border-zinc-700 shadow-2xl",
    fontFamily: "font-sans",
    isDark: true,
    bgImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&h=900&fit=crop",
    style: "granit",
  },
  {
    id: 10,
    name: "Hajnal",
    fantasyName: "Hajnal",
    description: "Világos, rózsaszínes-lavendulás lágy kora reggeli fények.",
    primaryColor: "#8b5cf6",
    secondaryColor: "#f5f3ff",
    accentColor: "#7c3aed",
    bgGradient: "from-violet-50 via-purple-50/50 to-indigo-50",
    cardBg: "bg-white/95 text-violet-950 border-violet-200 shadow-violet-100/50",
    fontFamily: "font-serif",
    isDark: false,
    bgImage: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=1600&h=900&fit=crop",
    style: "hajnal",
  },
];

export function getProfileTemplate(templateId: number | null | undefined): ProfileTemplate {
  return PROFILE_TEMPLATES.find((t) => t.id === templateId) ?? PROFILE_TEMPLATES[0];
}
